# Generated by Django 5.2 on 2025-04-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.TextField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_departamento', models.CharField(max_length=25)),
                ('gestor', models.CharField(max_length=50)),
                ('descrição', models.TextField(max_length=100)),
            ],
        ),
    ]
