# Generated by Django 5.1.6 on 2025-05-03 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_usuario_delete_conta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='descrição',
            field=models.TextField(max_length=5000),
        ),
    ]
