# Generated by Django 5.2.4 on 2025-09-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_departamento_descrição'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('sobrenome', models.CharField(max_length=25)),
                ('profissao', models.CharField(max_length=25)),
                ('numero', models.IntegerField(max_length=9)),
                ('email', models.EmailField(max_length=25)),
            ],
        ),
    ]
