# Generated by Django 5.2.4 on 2025-09-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_membros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membros',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
