# Generated by Django 5.2.4 on 2025-09-30 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_membros_numero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membros',
            old_name='numero',
            new_name='número',
        ),
        migrations.RenameField(
            model_name='membros',
            old_name='profissao',
            new_name='profissão',
        ),
    ]
