# Generated by Django 5.2.4 on 2025-09-30 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_numero_membros_número_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPonto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora_entrada', models.TimeField(blank=True, null=True)),
                ('hora_saida', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('presente', 'Presente'), ('falta', 'Falta'), ('justificada', 'Justificada')], default='presente', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trabalhador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('profissão', models.CharField(max_length=25)),
                ('número', models.IntegerField()),
                ('email', models.EmailField(max_length=25)),
                ('data_contratacao', models.DateField()),
                ('departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.departamento')),
            ],
        ),
        migrations.DeleteModel(
            name='Membros',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='registroponto',
            name='trabalhador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.trabalhador'),
        ),
    ]
