# Generated by Django 5.2.4 on 2025-10-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_registroponto_trabalhador_delete_membros_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhador',
            name='número',
            field=models.TextField(),
        ),
    ]
