# Generated by Django 5.2.4 on 2025-10-01 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_trabalhador_número'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhador',
            name='número',
            field=models.CharField(max_length=10),
        ),
    ]
