# Generated by Django 5.2.4 on 2025-10-01 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_trabalhador_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhador',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabalhadores', to='accounts.departamento'),
        ),
    ]
