# Generated by Django 5.2.4 on 2025-10-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_configuracaoplataforma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracaoplataforma',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
